### ISSUE TITLE
Compilation issue with the latest commits

### ISSUE THREAD

**Issue by msaharia** [NASA-LIS/LISF#126] opened 2019-05-20 20:02 UTC
I am running into this error with `./compile -j 24` and default configuration. This is on the latest commit `69c4496`. Any suggestions?

```
# 1 "../metforcing/pptEnsFcst/pptEnsFcst_SpatialInterpMod.F90"
^
../metforcing/pptEnsFcst/pptEnsFcst_SpatialInterpMod.F90: warning #5462: Global name too long, shortened from: pptensfcst_spatialinterpmod_mp_pptensfcst_interp_finalize_$BLK.lis_mpimod_mp_mpi_errcodes_ignore_ to: ptensfcst_spatialinterpmod_mp_pptensfcst_interp_finalize_$BLK.lis_mpimod_mp_mpi_errcodes_ignore_
# 1 "../metforcing/pptEnsFcst/pptEnsFcst_SpatialInterpMod.F90"
^
../dataassim/obs/LDT_SI/write_LDTSIobs.F90(39): error #6780: A dummy argument with the INTENT(IN) attribute shall not be defined nor become undefined.   [OBS_STATE]
   call ESMF_AttributeGet(OBS_State, "Data Update Status", &
--------------------------^
compilation aborted for ../dataassim/obs/LDT_SI/write_LDTSIobs.F90 (code 1)
make: *** [write_LDTSIobs.o] Error 1
make: *** Waiting for unfinished jobs....

[ERR] Compile failed
```

**Comment by msaharia** [comment] 2019-05-20 20:17
I have reverted to an earlier commit for now. Compiles fine at `e8f21e7`.

**Comment by dmocko** [comment] 2019-05-23 18:21
Thanks - we are investigating this issue.  We don't see it with the Intel-18 compiler.  What compiler (and version) are you using?

**Comment by emkemp** [comment] 2019-05-28 15:47
Hello:

We are unable to reproduce your error on Discover with Intel 18 or 14 (using LIS team modules).  Can you please provide us with more information on what compiler and module you were using?  Otherwise, we will have to close this ticket.

**Comment by emkemp** [comment] 2019-05-28 16:36
Also, I just tested this with the LIS team's GCC 7.3 module.  Still cannot reproduce the error.

**Comment by msaharia** [comment] 2019-05-28 16:37
Here is my entire bash:


```
# -------------------------------------------------------------------
# LIS
# -------------------------------------------------------------------

PATH=$HOME/bin:$PATH

export LIBGL_ALWAYS_INDIRECT=1

export PATH=/discover/nobackup/projects/lis/libs/netcdf/4.3.3.1_intel-14.0.3.174_sp3/bin/:$PATH
export PATH=/usr/local/other/SLES11.1/ncl/6.2.0/intel-12.1.0.233/bin/:$PATH
export PATH=/usr/local/other/SLES11.3/python/2.7.11/gcc-4.3.4/bin:$PATH

ulimit -v unlimited
ulimit -s unlimited

#load NetCDF modules
alias ncview=/discover/nobackup/projects/lis/libs/ncview/2.1.1/bin/ncview
alias ncdump=/discover/nobackup/projects/lis/libs/netcdf/4.3.3.1_intel-14.0.3.174_sp3/bin/ncdump

#Grads
GASCRP=/home/svkumar/grads/lib/scripts
export GASCRP
alias grads='/discover/nobackup/projects/gmao/share/dasilva/opengrads/Contents/grads -g 1100x850+70+0'

# load NCL module
export NCARG_ROOT=/usr/local/other/SLES11.1/ncl/6.2.0/intel-12.1.0.233/
export NCARG_COLORMAPS=/home/agetiran/colormaps:${NCARG_ROOT}/lib/ncarg/colormaps

export SVN_EDITOR=emacs
export GAVERSION=2.0.1.oga.1
module purge
module load comp/intel-14.0.3.174
module load mpi/impi-5.0.3.048
#module load other/vim-7.1
module load other/svn-1.8.13
module load lib/mkl-10.1.2.024
module load tool/tview-2016.07.22
module load other/ncl-6.3.0-static
module load tool/matlab-R2017b
#module load tool/matlab-R2014a

export DEV_ENV=7_INTEL_14_SP3

export LIS_SRC=/home/[username]/[src_directory]
export LIS_ARCH=linux_ifc
export LIS_SPMD=parallel
export LIS_FC=mpif90
export LIS_CC=mpicc
export LIS_JASPER=/discover/nobackup/projects/lis/libs/jasper/1.900.1_intel-14.0.3.174_sp3
export LIS_GRIBAPI=/discover/nobackup/projects/lis/libs/grib_api/1.12.3_intel-14.0.3.174_sp3
export LIS_NETCDF=/discover/nobackup/projects/lis/libs/netcdf/4.3.3.1_intel-14.0.3.174_sp3
export LIS_HDF4=/discover/nobackup/projects/lis/libs/hdf4/4.2.11_intel-14.0.3.174_sp3
export LIS_HDFEOS=/discover/nobackup/projects/lis/libs/hdfeos2/2.19v1.00_intel-14.0.3.174_sp3
export LIS_HDF5=/discover/nobackup/projects/lis/libs/hdf5/1.8.14_intel-14.0.3.174_sp3
export LIS_MODESMF=/discover/nobackup/projects/lis/libs/esmf/5.2.0rp3_intel-14.0.3.174_impi-5.0.3.048_sp3/mod/modO/Linux.intel.64.intelmpi.default
export LIS_LIBESMF=/discover/nobackup/projects/lis/libs/esmf/5.2.0rp3_intel-14.0.3.174_impi-5.0.3.048_sp3/lib/libO/Linux.intel.64.intelmpi.default
export LIS_MINPACK=
export LIS_CRTM=
export LIS_CRTM_PROF=
export LIS_CMEM=

export LD_LIBRARY_PATH=${LIS_HDF4}/lib:${LIS_HDF5}/lib:${LIS_LIBESMF}:${LIS_NETCDF}/lib:${LIS_GRIBAPI}/lib:{LIS_JASPER}/lib:$LD_LIBRARY_PATH
export LIS_GDAL=/discover/nobackup/projects/lis/libs/gdal/2.0.0/
export LIS_FORTRANGIS=/discover/nobackup/projects/lis/libs/fortrangis/2.4/

export LVT_ARCH=linux_ifc
export LVT_FC=mpif90
export LVT_CC=mpicc
export LVT_JASPER=/discover/nobackup/projects/lis/libs/jasper/1.900.1_intel-14.0.3.174_sp3
export LVT_GRIBAPI=/discover/nobackup/projects/lis/libs/grib_api/1.12.3_intel-14.0.3.174_sp3
export LVT_NETCDF=/discover/nobackup/projects/lis/libs/netcdf/4.3.3.1_intel-14.0.3.174_sp3
export LVT_HDF4=/discover/nobackup/projects/lis/libs/hdf4/4.2.11_intel-14.0.3.174_sp3
export LVT_HDFEOS=/discover/nobackup/projects/lis/libs/hdfeos2/2.19v1.00_intel-14.0.3.174_sp3
export LVT_HDF5=/discover/nobackup/projects/lis/libs/hdf5/1.8.14_intel-14.0.3.174_sp3
export LVT_MODESMF=/discover/nobackup/projects/lis/libs/esmf/5.2.0rp3_intel-14.0.3.174_impi-5.0.3.048_sp3/mod/modO/Linux.intel.64.intelmpi.default
export LVT_LIBESMF=/discover/nobackup/projects/lis/libs/esmf/5.2.0rp3_intel-14.0.3.174_impi-5.0.3.048_sp3/lib/libO/Linux.intel.64.intelmpi.default
export LVT_GDAL=/discover/nobackup/projects/lis/libs/gdal/2.0.0/
export LVT_FORTRANGIS=/discover/nobackup/projects/lis/libs/fortrangis/2.4/


# Intel (Kristi):
export LDT_ARCH=linux_ifc
export LDT_FC=mpif90
export LDT_CC=mpicc
export LDT_JASPER=/discover/nobackup/projects/lis/libs/jasper/1.900.1_intel-14.0.3.174_sp3
export LDT_GRIBAPI=/discover/nobackup/projects/lis/libs/grib_api/1.12.3_intel-14.0.3.174_sp3
export LDT_NETCDF=/discover/nobackup/projects/lis/libs/netcdf/4.3.3.1_intel-14.0.3.174_sp3
export LDT_HDF4=/discover/nobackup/projects/lis/libs/hdf4/4.2.11_intel-14.0.3.174_sp3
export LDT_HDFEOS=/discover/nobackup/projects/lis/libs/hdfeos2/2.19v1.00_intel-14.0.3.174_sp3
export LDT_HDF5=/discover/nobackup/projects/lis/libs/hdf5/1.8.14_intel-14.0.3.174_sp3
export LDT_MODESMF=/discover/nobackup/projects/lis/libs/esmf/5.2.0rp3_intel-14.0.3.174_impi-5.0.3.048_sp3/mod/modO/Linux.intel.64.intelmpi.default
export LDT_LIBESMF=/discover/nobackup/projects/lis/libs/esmf/5.2.0rp3_intel-14.0.3.174_impi-5.0.3.048_sp3/lib/libO/Linux.intel.64.intelmpi.default
export LDT_GDAL=/discover/nobackup/projects/lis/libs/gdal/2.0.0/
export LDT_FORTRANGIS=/discover/nobackup/projects/lis/libs/fortrangis/2.4/

#export LD_LIBRARY_PATH=$LDT_HDF4/lib:$LDT_HDF5/lib:$LDT_LIBESMF:$LDT_NETCDF/lib:$LDT_GRIBAPI/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${LIS_HDF4}/lib:${LIS_HDF5}/lib:${LIS_LIBESMF}:${LIS_NETCDF}/lib:${LIS_GRIBAPI}/lib:${LIS_GDAL}/lib:$LD_LIBRARY_PATH

export LDFLAGS="-L/$HOME -lpng -lz"
export ARFLAGS=ruv
```
I just checked again and can reproduce the error.

**Comment by emkemp** [comment] 2019-05-28 16:38
Thanks for the update.  I'll play with this.

**Comment by emkemp** [comment] 2019-05-28 21:08
Hello:

It turns out I was compiling the wrong program (LDT instead of LIS).  When I compile LIS with the Intel 14 module, I reproduce your error.

The error is not with the compiler, but with a change in the ESMF library API.  (The Intel 14 module uses ESMF 5.2.0rp3, while the Intel 18 module uses ESMF 7.1.0r).

The easy fix is to change write_LDTSIobs.F90 from:

type(ESMF_State), intent(in) :: OBS_State

to

type(ESMF_State), intent(inout) :: OBS_State

That should be compatible with both ESMF versions.  I will merge a patch to the GitHub repository shortly.

Sorry for the confusion!

**Comment by msaharia** [comment] 2019-05-30 22:50
@emkemp A little aside, should a new feature PR be made against the latest commit on the support branch or the master branch? The manual ([Here](https://github.com/NASA-LIS/LISF/blob/master/docs/working_with_github/working_with_github.adoc#47-step-5-issue-a-pull-request)) prescribes `master` always, but obviously, the recent commits on this branch need to be merged first.

**Comment by emkemp** [comment] 2019-05-31 17:28
@msaharia  We distinguish between "feature" and "fix" pull requests.  Feature PRs should be made against the latest commit in master (unless the feature is for a specific project and that project has it's own support branch--a situation we are trying to avoid).  In contrast, fix PRs should be made against a support branch.  

@jvgeiger is sanity checking the latest bug fixes in the support/lisf-557ww-7.3 branch before migrating to master.  Hopefully that will be complete by the end of today.

**Comment by emkemp** [comment] 2019-05-31 19:23
Hi @msaharia:

@jvgeiger merged the latest changes back into master.  Can you please pull the latest updates and see if you still have your compiling problem?

**Comment by msaharia** [comment] 2019-05-31 19:34
@emkemp Compiled successfully at latest commit - confirmed.

**Comment by emkemp** [comment] 2019-05-31 19:35
Excellent!  We will close this ticket. Thanks!

**Closed by emkemp** 2019-05-31 19:35 UTC
Labels: bug
